### ISSUE TITLE
Front matter 在文档编辑后覆盖的问题

### ISSUE THREAD

**Issue by gylidian** [gaoyoubo/hexo-client#32]
某些主题下需要手动指定诸如 `thumbnail: xxx.jpg` `comments:true` 属性
而HexoClient中每当markdown编辑完之后都会将front matter重新覆盖（也就是说，上述的属性都被清空）

**Comment by gaoyoubo** [comment]
@gylidian 好的，我看下这个问题。

**Comment by gylidian** [comment]
@gaoyoubo 建议添加一个文本框放置额外的front matter，这样就不用一个一个打开相应文件添加了😭

**Comment by nygula** [comment]
同样是这个问题 , 修改后的文章比原本的文章要长很多, front matter里面增加了一个存放历史的字段...

**Comment by gaoyoubo** [comment]
@nygula 感谢反馈，我看下怎么修复。

**Comment by gaoyoubo** [comment]
@gylidian @nygula 方便提供下你们的 Front matter 示例吗？

**Comment by gylidian** [comment]
我手动在文件夹开了个新.md文件，front matter 如下
```yaml
title: testtesttest
thumbnail: 'testtest.png'
tags:
  - 哈哈
categories:
  - test
toc: true
comments: true
date: 2019-03-01 22:01:10
```
当我在 HexoClient 中编辑后，就会被覆盖成下面的样子
```yaml
title: 哈哈哈哈哈哈哈哈哈哈
tags:
  - 哈哈
originContent: ''
categories:
  - test
toc: true
date: 2019-03-01 22:01:10
```
